import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="main_background">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 60%;
    margin: 0 auto; */}

      <Header />

      <main className="w-full h-full">
        <section className='w-full h-full flex flex-col justify-center items-center gap-12 mx-auto my-0 text-center z-10 bg-black/50 opacity-7'>
          <div className='flex items-center w-fit'>
            <h1 className='text-4xl font-bold text-white'>Open the world of muisc. <br/>It's all here.</h1>                        
          </div>
          <div>
          <div className='flex gap-2'>
            <button className='rounded-full bg-gradient-to-r from-bluish_1 to-purple_1 px-4 text-1xl font-bold text-white h-9'>MUSICBOX PREMIUM</button>
            <button className='border-2 border-white rounded-full px-4 text-1xl font-bold text-white h-9'>MUSICBOX FREE</button>
          </div>
          <p className='text-white mt-4'>1-month free trial <span className='text-bluish'>$7.99</span>/month after</p>
          </div>

        </section>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home;



